# Generated by Django 4.0.6 on 2022-07-13 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agresor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('documento', models.CharField(blank=True, max_length=15)),
                ('telefono', models.CharField(blank=True, max_length=24)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('fecha_nacimiento', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('agresor', models.ManyToManyField(to='casos.agresor')),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=100)),
                ('altura', models.IntegerField()),
                ('piso_depto', models.CharField(blank=True, max_length=10)),
                ('codigo_postal', models.CharField(blank=True, max_length=12)),
                ('localidad', models.CharField(max_length=100)),
                ('provincia', models.CharField(choices=[('AR-C', 'CABA'), ('AR-B', 'Buenos Aires'), ('AR-K', 'Catamarca'), ('AR-H', 'Chaco'), ('AR-U', 'Chubut'), ('AR-X', 'Córdoba'), ('AR-W', 'Corrientes'), ('AR-E', 'Entre Ríos'), ('AR-P', 'Formosa'), ('AR-Y', 'Jujuy'), ('AR-L', 'La Pampa'), ('AR-F', 'La Rioja'), ('AR-M', 'Mendoza'), ('AR-N', 'Misiones'), ('AR-Q', 'Neuquén'), ('AR-R', 'Río Negro'), ('AR-A', 'Salta'), ('AR-J', 'San Juan'), ('AR-D', 'San Luis'), ('AR-Z', 'Santa Cruz'), ('AR-S', 'Santa Fe'), ('AR-G', 'Santiago del Estero'), ('AR-V', 'Tierra del Fuego'), ('AR-T', 'Tucumán'), ('None', '(sin especificar)')], default='None', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Victima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('documento', models.CharField(blank=True, max_length=15)),
                ('telefono', models.CharField(blank=True, max_length=24)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='casos.domicilio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('nombre', models.TextField()),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casos.caso')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('archivo', models.FileField(upload_to='')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casos.caso')),
                ('incidencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='casos.incidencia')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=24)),
                ('email', models.CharField(max_length=50, null=True)),
                ('victima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casos.victima')),
            ],
        ),
        migrations.AddField(
            model_name='caso',
            name='victima',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='casos.victima'),
        ),
        migrations.AddField(
            model_name='agresor',
            name='domicilio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='casos.domicilio'),
        ),
    ]
